# Question-1
## Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

arr1 = np.arange(2, 51, 3)

print(arr1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question-2
## Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [18]:
lst1, lst2 = [], []
n = 1
while n<=2:
    
    for i in range(5):
        lst_input = int(input())
        if n == 1:
            lst1.append(lst_input)
        else:
            lst2.append(lst_input)
    n+=1

arr1 = np.array(lst1)
arr2 = np.array(lst2)

array_concat = np.concatenate((arr1, arr2))
print('Concatinated Array:',array_concat)

print('Sorted Array:', np.sort(array_concat))

43
12
54
87
23
98
23
48
92
45
Concatinated Array: [43 12 54 87 23 98 23 48 92 45]
Sorted Array: [12 23 23 43 45 48 54 87 92 98]


# Question-3
## Write a code snippet to find the dimensions of a ndarray and its size.

In [24]:
Sample_array = np.array([
                            [1,2,3],
                            [4,5,6],
                            [7,8,9]
                        ])
print('Dimensions:',Sample_array.ndim)

print('Size:', Sample_array.size)

Dimensions: 2
Size: 9


# Question-4
## How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr = np.reshape(arr, (3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.expand_dims(arr, axis = 1)
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# Question-5
## Consider two square numpy arrays. Stack them vertically and horizontally.

In [65]:
sq_arr1 = np.square([2,3,4])
sq_arr2 = np.square([5,6,7])

print('Vertical Stack:')
print(np.vstack((sq_arr1,sq_arr2)))

print('Horizontal stack:')
print(np.hstack((sq_arr1,sq_arr2)))

Vertical Stack:
[[ 4  9 16]
 [25 36 49]]
Horizontal stack:
[ 4  9 16 25 36 49]


# Question-6
## How to get unique items and counts of unique items?

In [94]:
arr = np.array([4, 7, 8, 9, 5, 6, 5, 4, 4])
arr1, arr2 = np.unique(arr, return_counts=True)

d ={}

for i in range(len(arr1)):
    d[arr1[i]]=arr2[i]

count = 0
print('Unique Values are: ')

for i in d:
    if d[i]==1:
        print(i)
        count += 1
print('Count of unique values:', count)

Unique Values are: 
6
7
8
9
Count of unique values: 4


## Thank You LetsUpgrade